import type { Product } from '@/types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'PC Bureau Gamer Pro X',
    description: 'Tour gaming haute performance avec processeur Intel Core i7, 32 Go RAM DDR5, carte graphique RTX 4070. Idéal pour le gaming et le montage vidéo.',
    price: 4500000,
    originalPrice: 5200000,
    currency: 'Ar',
    category: 'pc-bureau',
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400&q=80'],
    rating: 4.9,
    reviewCount: 127,
    stock: 10,
    badge: 'bestseller',
    origin: 'Assemblé à Antananarivo',
    tags: ['pc', 'gaming', 'bureau', 'intel', 'RTX'],
  },
  {
    id: 'p2',
    name: 'Carte Graphique RTX 4060 Ti',
    description: 'NVIDIA GeForce RTX 4060 Ti 8 Go GDDR6. Ray tracing, DLSS 3.0, idéale pour le gaming 1080p/1440p ultra. Refroidissement triple ventilateurs.',
    price: 1850000,
    currency: 'Ar',
    category: 'carte-graphique',
    images: ['https://images.unsplash.com/photo-1591488320449-011701bb6704?w=400&q=80'],
    rating: 4.7,
    reviewCount: 89,
    stock: 15,
    badge: 'new',
    origin: 'NVIDIA / ASUS',
    tags: ['GPU', 'nvidia', 'RTX', 'gaming', 'graphique'],
  },
  {
    id: 'p3',
    name: 'PC Portable Ultrabook 14"',
    description: 'Laptop ultra-fin 14 pouces, Intel Core i5 13ème génération, 16 Go RAM, SSD 512 Go. Autonomie 12h, poids 1,3 kg. Parfait pour les professionnels.',
    price: 2800000,
    currency: 'Ar',
    category: 'pc-portable',
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80'],
    rating: 4.8,
    reviewCount: 54,
    stock: 20,
    badge: 'bestseller',
    origin: 'Lenovo / Dell',
    tags: ['laptop', 'ultrabook', 'portable', 'bureau', 'léger'],
  },
  {
    id: 'p4',
    name: 'RAM DDR5 32 Go 6000MHz',
    description: 'Kit 2x16 Go DDR5 6000MHz avec dissipateur thermique RGB. Compatible Intel et AMD. Latence CL36, idéale pour gaming et workstation.',
    price: 480000,
    originalPrice: 550000,
    currency: 'Ar',
    category: 'ram',
    images: ['https://media.ldlc.com/r705/ld/products/00/05/90/31/LD0005903154_1_0005921485_0005953604_0005988579.jpg'],
    rating: 5.0,
    reviewCount: 31,
    stock: 40,
    badge: 'sale',
    origin: 'Corsair / G.Skill',
    tags: ['RAM', 'DDR5', 'mémoire', 'gaming', 'RGB'],
  },
  {
    id: 'p5',
    name: 'Processeur AMD Ryzen 9 7900X',
    description: 'CPU AMD Ryzen 9 7900X, 12 cœurs / 24 threads, 4.7 GHz boost. Architecture Zen 4, socket AM5. Performances exceptionnelles en création et gaming.',
    price: 1200000,
    currency: 'Ar',
    category: 'processeur',
    images: ['https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=400&q=80'],
    rating: 4.9,
    reviewCount: 73,
    stock: 18,
    badge: 'local',
    origin: 'AMD',
    tags: ['CPU', 'AMD', 'Ryzen', 'processeur', 'workstation'],
  },
  {
    id: 'p6',
    name: 'SSD NVMe 1 To PCIe 4.0',
    description: 'Disque SSD M.2 NVMe 1 To, lecture 7000 Mo/s, écriture 6500 Mo/s. Format 2280, compatible PCIe 4.0. Chargements ultra-rapides.',
    price: 320000,
    currency: 'Ar',
    category: 'stockage',
    images: ['https://images.unsplash.com/photo-1601737487795-dab272f52420?w=400&q=80'],
    rating: 4.6,
    reviewCount: 42,
    stock: 35,
    badge: 'new',
    origin: 'Samsung / WD Black',
    tags: ['SSD', 'NVMe', 'stockage', 'rapide', 'M.2'],
  },
  {
    id: 'p7',
    name: 'Moniteur Gaming 27" 165Hz',
    description: 'Écran IPS 27 pouces, résolution QHD 2560x1440, 165Hz, 1ms. HDR400, compatible FreeSync Premium et G-Sync. Couleurs éclatantes pour le gaming.',
    price: 1350000,
    currency: 'Ar',
    category: 'peripherique',
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80'],
    rating: 4.8,
    reviewCount: 96,
    stock: 12,
    badge: 'bestseller',
    origin: 'LG / ASUS ROG',
    tags: ['moniteur', 'gaming', 'QHD', '165Hz', 'IPS'],
  },
  {
    id: 'p8',
    name: 'Clavier Mécanique RGB TKL',
    description: 'Clavier mécanique tenkeyless, switchs Cherry MX Red, rétroéclairage RGB par touche. Boîtier aluminium, anti-ghosting complet, câble USB-C tressé.',
    price: 275000,
    currency: 'Ar',
    category: 'peripherique',
    images: ['https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&q=80'],
    rating: 4.5,
    reviewCount: 158,
    stock: 50,
    origin: 'Keychron / Ducky',
    tags: ['clavier', 'mécanique', 'RGB', 'gaming', 'TKL'],
  },
]

import {
  LayoutGrid,
  Monitor,
  Cpu,
  HardDrive,
  Laptop,
  MemoryStick,
  Layers,
  Keyboard,
} from "lucide-react";

export const CATEGORIES = [
  { id: 'all',             label: 'Tout',            icon: LayoutGrid },
  { id: 'pc-bureau',       label: 'PC Bureau',       icon: Monitor },
  { id: 'pc-portable',     label: 'PC Portable',     icon: Laptop },
  { id: 'carte-graphique', label: 'Carte Graphique', icon: Layers },
  { id: 'ram',             label: 'RAM',             icon: MemoryStick },
  { id: 'processeur',      label: 'Processeur',      icon: Cpu },
  { id: 'stockage',        label: 'Stockage',        icon: HardDrive },
  { id: 'peripherique',    label: 'Périphériques',   icon: Keyboard },
];