import type { Product } from '@/types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Vanille Bourbon de Madagascar',
    description: 'Gousses de vanille premium, cultivées dans la région de SAVA. Arôme intense et floral, idéale pour la pâtisserie et les desserts raffinés.',
    price: 18000,
    originalPrice: 22000,
    currency: 'Ar',
    category: 'epices',
    images: ['https://www.vanissa.fr/cdn/shop/files/Vanille_de_Madagascar_et_Ouganda_5e34e249-4b12-4590-b6f1-996b9dbfd90b_720x.jpg?v=1748444862'],
    rating: 4.9,
    reviewCount: 127,
    stock: 45,
    badge: 'bestseller',
    origin: 'SAVA, Madagascar',
    tags: ['vanille', 'épices', 'bio', 'premium'],
  },
  {
    id: 'p2',
    name: 'Huile Essentielle Ylang-Ylang',
    description: 'Distillée à la vapeur d\'eau, cette huile pure de ylang-ylang possède un parfum floral envoûtant. Idéale pour l\'aromathérapie.',
    price: 12500,
    currency: 'Ar',
    category: 'huiles',
    images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&q=80'],
    rating: 4.7,
    reviewCount: 89,
    stock: 30,
    badge: 'local',
    origin: 'Nosy Be, Madagascar',
    tags: ['huile essentielle', 'aromathérapie', 'parfum'],
  },
  {
    id: 'p3',
    name: 'Panier Tressé Artisanal',
    description: 'Panier en raphia tressé à la main par les artisanes de la Région Vakinankaratra. Chaque pièce est unique.',
    price: 35000,
    currency: 'Ar',
    category: 'artisanat',
    images: ['https://images.unsplash.com/photo-1776721976768-7a392044d0f2?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    rating: 4.8,
    reviewCount: 54,
    stock: 12,
    badge: 'new',
    origin: 'Antsirabe, Madagascar',
    tags: ['raphia', 'artisanat', 'fait main', 'décoration'],
  },
  {
    id: 'p4',
    name: 'Tissu Lamba Mena Traditionnel',
    description: 'Lamba authentique en soie sauvage, aux couleurs naturelles extraites de plantes locales. Symbole de la culture malgache.',
    price: 85000,
    originalPrice: 95000,
    currency: 'Ar',
    category: 'textile',
    images: ['https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&q=80'],
    rating: 5.0,
    reviewCount: 31,
    stock: 8,
    badge: 'sale',
    origin: 'Ambositra, Madagascar',
    tags: ['lamba', 'soie', 'textile', 'traditionnel', 'cérémonies'],
  },
  {
    id: 'p5',
    name: 'Poivre Sauvage Voatsiperifery',
    description: 'Poivre grimpant rare, récolté en forêt tropicale. Notes de genièvre et de citron. L\'un des poivres les plus recherchés au monde.',
    price: 28000,
    currency: 'Ar',
    category: 'epices',
    images: ['https://doretdepices.com/wp-content/uploads/2025/06/poivre-noir-sauvage-25g-de-madagascar.jpg'],
    rating: 4.9,
    reviewCount: 73,
    stock: 20,
    badge: 'local',
    origin: 'Forêts du Sud-Est',
    tags: ['poivre', 'épices', 'rare', 'gastronomie'],
  },
  {
    id: 'p6',
    name: 'Bijoux Labradorite Artisanal',
    description: 'Pendentif en labradorite de Madagascar, monture en argent 925. Pierre aux reflets irisés bleutés, polie à la main.',
    price: 125000,
    currency: 'Ar',
    category: 'bijoux',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&q=80'],
    rating: 4.6,
    reviewCount: 42,
    stock: 5,
    badge: 'new',
    origin: 'Ihosy, Madagascar',
    tags: ['bijoux', 'labradorite', 'argent', 'pierre précieuse'],
  },
  {
    id: 'p7',
    name: 'Miel de Litchi Pur',
    description: 'Miel récolté dans les vergers de litchis de la côte Est. Texture crémeuse, notes fruitées. 100% naturel, non pasteurisé.',
    price: 15000,
    currency: 'Ar',
    category: 'alimentaire',
    images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&q=80'],
    rating: 4.8,
    reviewCount: 96,
    stock: 60,
    badge: 'bestseller',
    origin: 'Tamatave, Madagascar',
    tags: ['miel', 'litchi', 'naturel', 'bio'],
  },
  {
    id: 'p8',
    name: 'Huile de Coco Vierge Bio',
    description: 'Pressée à froid à partir de noix de coco fraîches. Idéale pour la cuisine, la peau et les cheveux. Certifiée biologique.',
    price: 9500,
    currency: 'Ar',
    category: 'huiles',
    images: ['https://www.savanna-spices.fr/wp-content/uploads/2023/07/Huile-coco.png'],
    rating: 4.5,
    reviewCount: 158,
    stock: 80,
    origin: 'Morondava, Madagascar',
    tags: ['coco', 'huile', 'bio', 'cosmétique'],
  },
]

import {
  LayoutGrid,
  Leaf,
  Droplet,
  Palette,
  Shirt,
  Gem,
  Utensils
} from "lucide-react";

export const CATEGORIES = [
  { id: 'all',         label: 'Tout',        icon: LayoutGrid },
  { id: 'epices',      label: 'Épices',      icon: Leaf },
  { id: 'huiles',      label: 'Huiles',      icon: Droplet },
  { id: 'artisanat',   label: 'Artisanat',   icon: Palette },
  { id: 'textile',     label: 'Textile',     icon: Shirt },
  { id: 'bijoux',      label: 'Bijoux',      icon: Gem },
  { id: 'alimentaire', label: 'Alimentaire', icon: Utensils },
];
